-- phpMyAdmin SQL Dump
-- version 4.8.0.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Apr 01, 2019 at 06:46 PM
-- Server version: 10.1.32-MariaDB
-- PHP Version: 7.2.5

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `books`
--

-- --------------------------------------------------------

--
-- Table structure for table `bme`
--

CREATE TABLE `bme` (
  `Title` varchar(60) NOT NULL,
  `Author` varchar(60) NOT NULL,
  `Quantity` int(3) NOT NULL,
  `Img_Path` varchar(60) NOT NULL,
  `Description` varchar(2000) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `bme`
--

INSERT INTO `bme` (`Title`, `Author`, `Quantity`, `Img_Path`, `Description`) VALUES
('Bioelectricity', 'Roger C. Barr', 70, 'Books frontpage/BME/Be.jpg', 'Through the management of electrons as well as electrolytes, a bioelectrical charge can move throughout our body sending critical messages, impulses and signals which manage every process in our body. Unlike the current allopathic approach which tries its best but is oftentimes focused on non-holistic biochemicals and hyper-targeting, a renewed effective bioelectrical strategy allows us to open a blockage, thereby unleashing the natural resources of the body to bring us back to homeostasis and heal. We are bioelectrical machines and this book gives us that theoretical understanding. The Tam Healing System has revived this paradigm and brought it to a new level. When the biophysical electrical properties of the tissues are considered, it makes sense to develop therapeutic strategies that support the body?s biophysical electrical processes to potentiate the healing of injured, diseased, cancerous tissues.'),
('Biomathematics', 'I N Defares', 70, 'Books frontpage/BME/Bm.jpg', 'The book is a textbook (with many exercises) giving an in-depth account of the practical use of mathematical modelling in the biomedical sciences. The mathematical level required is generally not high and the emphasis is on what is required to solve the real biological problem. The subject matter is drawn, e.g. from population biology, reaction kinetics, biological oscillators and switches, Belousov-Zhabotinskii reaction, reaction-diffusion theory, biological wave phenomena, central pattern generators, neural models, spread of epidemics, mechanochemical theory of biological pattern formation and importance in evolution. Most of the models are based on real biological problems and the predictions and explanations offered as a direct result of mathematical analysis of the models are important aspects of the book. The aim is to provide a thorough training in practical mathematical biology and to show how exciting and novel mathematical challenges arise from a genuine interdisciplinary involvement with the biosciences. The book also shows how mathematics can contribute to the science of the next 100 years and how physical scientists must get involved. It presents a broad view of the field of theoretical and mathematical biology and is a good starting place from which to start genuine interdisciplinary research.'),
('Biorheology', 'Isamu Kaneda', 70, 'Books frontpage/BME/Br.jpg', 'In this book, a wide range subjects in biorheology are dealt with, from fundamentals to applications. The inclusion of quite substantial chapters concerned with application aspects such as the latest studies on foods, cosmetics, personal care products, and biological tissues, related regenerative medicine, is one of the features of the book. For the fundamental aspects, studies on the physicochemical characteristics of biopolymer, the key substance of soft matter, are listed. By contrast, in the application aspect, although the main topic is the rheology of foods, focusing on the \"texture\" of mastication or swallowing, novel studies on cosmetics and personal care products concerning feeling during the lubrication by those products are also considered.'),
('Biostatistics', 'Geoffrey R Norman', 80, 'Geoffrey R Norman', 'Thoroughly revised and updated, the second edition of Intuitive Biostatistics retains and refines the core perspectives of the previous edition: a focus on how to interpret statistical results rather than on how to analyze data, minimal use of equations, and a detailed review of assumptions and common mistakes. Biostatistics, Completely Revised Second Edition, provides a clear introduction to statistics for undergraduate and graduate students and also serves as a statistics refresher for working scientists. '),
('Lasers in Medicine', 'Donald C. O\'Shea', 80, 'Books frontpage/BME/LM.jpg', 'This book is designed to fill the gap between brief reviews of lasers provided in modern physical optics texts and the thorough, graduate-level texts on lasers an quantum mechanics. For those students who may not want to invest a substantial amount of their elective time in extensive course work in this area, it represents a reasonable alternative to a more lengthy treatment.');

-- --------------------------------------------------------

--
-- Table structure for table `ce`
--

CREATE TABLE `ce` (
  `Title` varchar(60) NOT NULL,
  `Author` varchar(60) NOT NULL,
  `Quantity` int(3) NOT NULL,
  `Img_Path` varchar(60) NOT NULL,
  `Description` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `ce`
--

INSERT INTO `ce` (`Title`, `Author`, `Quantity`, `Img_Path`, `Description`) VALUES
('Bridge Engineering', 'Rangwala', 80, 'Books frontpage/CE/BE.jpg', 'This new reference work addresses both the maintenance and the upkeep of existing movable bridges, as well as the complete design of new movable bridges. Comprehensive coverage is provided on engineering design and actual construction technology used in building all major types of bridges, including all structural issues and relevant mechanical and electrical systems used to make such bridges functional. Includes coverage of vertical lift, swing, and bascule bridges for both highway and railway usage Offers valuable guidance on operation, maintenance, inspection, and rehabilitation of moveable bridges'),
('Building Drawing', 'S.S. Bhavikatti', 80, 'Books frontpage/CE/BD.jpg', 'This book deals with good ventilation, thermal comfort, and acoustic requirements when planning a building. As well as satisfying minimum standards and the regulations of local authorities, economics and future expansions are considered. The book discusses building drawings created through computer aided design. To understand the commands of AutoCAD and use them, the sequential procedure and steps involved while drawing plan, elevation and section are stored as screen captures and collection of these screen shots are placed in a CD which is enclosed with this book. The practising engineer will also find it as an excellent reference book.'),
('Concrete Technology', 'M S Shetty', 70, 'Books frontpage/CE/CT.jpg', 'This book gives students of Civil Engineering a thorough understanding of all aspects of concrete technology from first principles. It covers types of Cement, Admixtures, Concrete strength, durability and testing with reference to national standards.\r\nFor more than 30 years, the book has evolved to be a must-read for all students of the subject and has also been a useful reference book for practicing engineers.'),
('Earthquake Engineering', 'Nazzal Armouti', 80, 'Books frontpage/CE/EEE.jpg', 'It is a guide that puts into practice the concepts behind seismic codes into the planning of buildings. It also talks about the fundamentals of structural dynamic, along with a discussion on engineering seismology. It touches upon various subjects which are a part of the process of Earthquake Resistant Design (ERD) and help when establishing earthquake resistant buildings. Earthquake Resistant Design of Structures connects seismic design and ERD. The other topics it explains are the seismic zoning map of India and the motion studies prevalent in India.'),
('Environmental Engineering', 'Vitaly Prusov', 70, 'Books frontpage/CE/EE.jpg', 'This book brings together and integrates the three principal areas of environmental engineering water, air and solid waste management. It introduces a unique approach by emphasizing the relationship between the principles observed in natural purification processes and those employed in engineered systems. First, the physical, chemical, mathematical and biological principles that define, measure and quantify environmental quality are described. Next, the processes by which nature assimilates waste material are discussed and the natural purification processes that form the basis of engineered systems are detailed. Finally, the engineering principles and practices involved in the design and operation of environmental engineering works are covered at length.'),
('Foundation Engineering', 'Braja M. Das', 70, 'Books frontpage/CE/FE.jpg', 'This text presents the principles and practices for the selection and design of foundations of structures in a simple and concise manner. Codal references have been given to acquaint students with prevalent methodologies adopted in each country. The book also covers machine foundations, foundations on problematic soil and ground improvement techniques. Solved examples and multiple choice questions are included to help readers understand principles and memorise important details for practical application. The book is primarily intended for undergraduate and postgraduate students of civil engineering, though it will also be useful for research scholars and practicing engineers in the field.'),
('Ground Control', 'Anna Minton', 80, 'Books frontpage/CE/GC.jpg', 'This book teaches readers ground engineering principles and related mining and risk management practices associated with underground coal mining. It establishes the basic elements of risk management and the fundamental principles of ground behaviour and then applies these to the essential building blocks of any underground coal mining system, comprising excavations, pillars, and interactions between workings.\r\n\r\nReaders will also learn about types of ground support and reinforcement systems and their operating mechanisms. These elements provide the platform whereby the principles can be applied to mining practice and risk management, directed primarily to bord and pillar mining, pillar extraction, longwall mining, sub-surface and surface subsidence, and operational hazards.'),
('Hydraulic Structures', 'P. Novak', 70, 'Books frontpage/CE/HS.jpg', 'This book is a comprehensive book dealing with all the aspects of Irrigation in India starting from soil moisture to different types of irrigation systems like Sprinkler, Tubewell, Canal and Micro-Irrigation. It also focuses on Engineering Hydrology, Dams, Water Power Engineering as well as Irrigation Water Management. The book specially highlights the principles, practices and design procedures that have been widely recommended around the world.'),
('Hydraulics', 'Dr. Sadhu Singh', 80, 'Books frontpage/CE/H.jpg', 'This book provides a comprehensive coverage of fluid mechanics and hydraulics for various engineering courses. This text has been revised to incorporate SI units throughout the book. It starts with an overview, then covers Hydrostatics, study and measurement of Fluid Pressure and introduces Hydrokinematics. The book covers Floating Bodies and their Equilibrium, applications of Bernoulli’s equation, Flow through Orifices, Notches, Weirs, and Simple Pipes. It also covers how fluids flow through Open Channels and examines both uniform and non-uniform flows.'),
('Soil Mechanics', 'M. Palanikumar', 70, 'Books frontpage/CE/SM.jpg', 'This book  is written especially for students pursuing civil engineering. It provides a comprehensive understanding of soil characteristics and properties. It even contains experiments to help students gain a practical insight into soil mechanics. With all structures having earth as its common foundation, its essential that students of civil engineering understand this main component. A safe structure can only be built when there is thorough knowledge of its foundation.'),
('Strength of Materials', 'S. Timoshenko', 90, 'Books frontpage/CE/SOM.jpg', 'This book covers the syllabus in the subject of \"Strength of Materials\" of all the Indian Universities and Competitive Examinations as well. It contains experiments at the end of the chapters to enable the students to have an access to the practical aspects of the subject. It also contains typical examples (useful for students appearing in competitive examinations in particular and other students in general), highlights, objective type questions and a large number of unsolved examples. This book will prove a boon to the students appearing for engineering examinations as well as for Competitive Examinations.'),
('Structural Analysis', 'M Sharir', 70, 'Books frontpage/CE/SA.jpg', 'The book excels in providing students with a clear and thorough presentation of the theory and application of structural analysis as it applies to trusses, beams and frames. Emphasis is placed on teaching students to both model and analyses a structure. This text is shaped by the comments and suggestions of hundreds of reviewers in the teaching profession, as well as many of the author’s students. '),
('Structural Detailing', 'R.B. Asthana', 80, 'Books frontpage/CE/SD.jpg', 'Structural detailing consists of transforming the work of a structural engineer into working drawings for the use of the builder. The intended reader of this book is young and inexperienced and has not yet mastered bending moments and shearing forces, principal stresses and limit states, areas of steel and equivalent lengths. For this reason the book has been written for the reader with little or no prior knowledge of structural mechanics and simple explanations are given of the behaviour of structural components in service. Similarly it is assumed that the reader will have had little or no site experience and, in any case, will have little real understanding of the processes that are going on. Here, again, an attempt has been made to describe the construction process, insofar as it affects the work of the detailer. Throughout the text appropriate clauses and tables are quoted and, in part III, extracts are given, which will enable the reader to practice detailing other structures in stell, concrete and timber, following the examples given in each chapter.'),
('Surveying', 'A. Bannister', 80, 'Books frontpage/CE/S.jpg', 'This book has retained the necessary components that made the first edition unique. Starting with the basics, it gradually moves on to explain various concepts of surveying as well as levelling through lucid explanations, large number of illustrations, and adequate examples and exercise problems. '),
('Transportation Engineering', 'Kutz Myer', 80, 'Books frontpage/CE/TE.jpg', 'The book address issue and it is hoped that The engg. students studying transportation engg. will have a clear idea of The problem involved and how transportation engg. will have a clear idea of The problems involved and how they can be overcome in their professional career. Introduction Role of Transport in Society Mode of Transport Criteria for Choice Transport Planning History of Growth of Highway Dev. of Roads in India After Independence Geometric Design Survey and Project Preparation Embankment Design and Construction Highway Drainage Cross Drainage Structure Type of Pavement and Factor Governing Design of Flexible Pavement Design of Rigid Pavement Material Construction of Pavement Maintenance of Highway Use of Geosynthetic in Highway Engg. Urban Road Hill Road in Desert Area Toll Road Quality Assurance Highway Admin. and Finance Traffic Engg. Intro to Railway Engg. Railway Technology Role of Railway History of Growth of Railway in India Survey and Project Preparation Geometric Design of Railway Track Permanent Waypoint and Crossing Signalling and Traffic Control Traction and Resistance Station Yard and Equipment Construction of Railway Line Maintenance of Railway Line Track Renewal Bridge and Tunnel Rail Accident Modern Technological Advance Role of Air Transport Pipe Line Transport Aerial Ropeway Belt Conveyor Water Transport an Overview Planning for Water Transport Harbour Lock Entrance Docks Transit Shed Warehouse and Cargo Water Transport Multimodal Transport');

-- --------------------------------------------------------

--
-- Table structure for table `cse`
--

CREATE TABLE `cse` (
  `Title` varchar(60) NOT NULL,
  `Author` varchar(60) NOT NULL,
  `Quantity` int(3) NOT NULL,
  `Img_Path` varchar(60) NOT NULL,
  `Description` varchar(2000) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `cse`
--

INSERT INTO `cse` (`Title`, `Author`, `Quantity`, `Img_Path`, `Description`) VALUES
('Artificial Intelligence', 'Nilsson', 80, 'Books frontpage/CSE/AI.jpg', 'Intelligent agents are employed as the central characters in this new introductory text. Beginning with elementary reactive agents, Nilsson gradually increases their cognitive horsepower to illustrate the most important and lasting ideas in Al. Neural networks, genetic programming, computer vision, heuristic search, knowledge representation and reasoning, Bayes networks, planning, and language understanding are each revealed through the growing capabilities of these agents. The book provides a refreshing and motivating new synthesis of the field by one of Al\'s master expositors and leading researchers. Artificial Intelligence: A New Synthesis takes the reader on a complete tour of this intriguing new world of Al. Features: An evolutionary approach as a unifying theme, Thorough coverage of important Al ideas, old and new, Frequent use of examples and illustrative diagrams, Extensive coverage of machine learning methods throughout the text Citations to over 500 references and a Comprehensive index.'),
('Compiler Design', 'Alfred V. Aho', 80, 'Books frontpage/CSE/CR.jpg', 'The book provides a description about all the phases of a compiler which include lexical analysis, parsing, abstract syntax and semantic actions, intermediate representations, tree matching instruction selection, dataflow analysis, runtime systems and register allocations. The book also describes the techniques in code generation and register allocation and compilation of functional and object oriented languages. The book also provides a compilation of object oriented and functional languages, garbage collection, loop optimization, instruction scheduling and many others. The book includes discussion of both java and object oriented programming concepts.'),
('Computer Networks', 'Sudakshina Kundu', 80, 'Books frontpage/CSE/CN.jpg', 'This book provides introduction to various networking concepts which include TCP/IP protocols and internetworking. The book also discusses various fundamentals and scientific theories along with the details and examples which are taken from the latest technologies. The book also covers layering and packet formats for all the internet protocols. The different protocols are TCP, IPv4, IPv6, DHCP and DNS. The book also elaborates various trends in internet systems which include packet classification, software defined networking and mesh protocols. The book is very useful for students who want to learn more about TCP/IP protocols, internet architecture and many networking technologies.'),
('Data Communications & Networking', 'Forouzan', 80, 'Books frontpage/CSE/DCCN.jpg', 'We are pleased to present this edition of Forouzan\'s Data Communications and Networking. It has been developed specifically to meet the need of students of computer networks. In addition to a chapter on the peer-to-peer paradigm, a full chapter on quality of service (QoS), generous coverage of forward error correction, coverage of WiMAX and material on socket-interface programming in Java, we have added new end-of-chapter questions and problems to make the content more relevant and improve learning outcomes for the student.'),
('Database Management System', 'Navathe', 80, 'Books frontpage/CSE/DBMS.jpg', 'Database System Concepts by Silberschatz is now in its 6th edition and is one of the cornerstone texts of database education. It presents the fundamental concepts of database management in an intuitive manner geared toward allowing students to begin working with databases as quickly as possible. This book is designed for a first course in databases at the junior/senior undergraduate level or the first year graduate level. It also contains additional material that can be used as supplements or as introductory material for an advanced course. Because the authors present concepts as intuitive descriptions, a familiarity with basic data structures, computer organization, and a high-level programming language are the only prerequisites. Important theoretical results are covered, but formal proofs are omitted. In place of proofs, figures and examples are used to suggest why a result is true.'),
('Internet of Things', 'Arshdeep Bagha', 70, 'Books frontpage/CSE/IOT.jpg', 'This book is written as a textbook for educational programs at colleges and universities. It can also be used by IoT (Internet of Things) vendors and service providers for training their program developers. The authors have used an immersive \'hands on\' approach, similar to the one adopted in the companion book, Cloud Computing: A Hands-on Approach, to help readers gain expertise in developing working code for real-world IoT applications.'),
('Let Us C', 'Yashwanth Kanethkar', 80, 'Books frontpage/CSE/C.jpg', 'The book enumerates the concepts related to C Programming language, as prescribed by ANSI standard. The book elaborates on the basics of procedure oriented programming and the fundamentals of writing C codes. It goes on to cover aspects like functions and loops, learning which will help novice programmers to code elementary level codes properly.'),
('Machine Learning', 'Peter Harrington', 70, 'Books frontpage/CSE/ML.jpg', '“Machine Learning in Action” is a unique book that blends the foundational theories of machine learning with the practical realities of building tools for everyday data analysis. In it, you will use the flexible Python programming language to build programs that implement algorithms for data classification, forecasting, recommendations, and higher-level features like summarization and simplification. As you work through the numerous examples, you will explore key topics like classification, numeric prediction, and clustering. Along the way, you will be introduced to important established algorithms, such as Apriori, through which you identify association patterns in large datasets and Adaboost, a meta-algorithm that can increase the efficiency of many machine learning tasks. This book is written for hobbyists and developers. A background in Java is helpful-no prior experience with Android is assumed.'),
('Object oriented Programming in C++', 'E. Balagurusamy', 70, 'Books frontpage/CSE/C++.jpg', 'The book aims at providing an all-round enrichment of knowledge in the area of object-oriented programming with C++ as the implementation of language. The author has used simple language to explain critical concepts of object-oriented programming and for better understanding of the readers. The same concepts have been implemented in solved examples using C++ programming language. Retaining is original style of lucid writing, the books has ample solved examples, programming exercises and new practice questions. This revised edition has new projects and incorporates a couple of new elements like Learning Objectives and Limitations. The topic on Polymorphism has been revised and expanded for better understanding.'),
('Operating Systems', 'Galvin', 70, 'Books frontpage/CSE/OS.jpg', 'This book provides a clear understanding of all the the concepts that underlie operating systems. The book contains numerous examples that are relevant to operating systems like UNIX, Solaris, Windows NT, Apple, IBM and Linux. The emergence of java technology has lead to the illustration of important concepts in operating systems.The book nicely demonstrates topics like multitasking, CPU scheduling, process synchronisation, deadlock, security using the concept of java technology. There are numerous examples of operating systems like solaris, windows NT, linux. There is a separate chapter on threads which will make the students understand how the operating system schedules threads.'),
('Software Engineering', 'Rajib Mall', 80, 'Books frontpage/CSE/SE.jpg', 'This book has been restructured and revised to incorporate the latest advances in the field. It not only incorporates the latest and enhanced software engineering techniques and practices, but also shows how these techniques are applied into the practical software assignments. Chapters now incorporate illustrative examples to add an analytical insight on the subject. New to this edition: All chapters have been thoroughly revised. Objective questions have been included in all the chapters. More practice questions have been added. McCall\'s quality factors and ISO 9126 have been introduced in the chapter dealing with software quality assurance. Primarily intended for undergraduate students of computer science and engineering, the book will also be useful for students opting for a course in MCA, MBA and IT. Key features: Includes a large number of worked-out examples and practice problems. Chapter-end exercises and solutions to selected problems are included. A solutions manual is available for instructors.'),
('Theory of Automata and Computation', 'Hopcroft and Ulllman', 80, 'Books frontpage/CSE/TOAC.jpg', 'This book focuses on the core concepts used in modern programming languages and these core concepts include functions, type, memory management and control. The book also provides comprehensive presentation and comparison of the object oriented programming languages. The book contains separate chapters on history of objects, simula, smalltalk and languages like C++ and Java. The book also introduces fundamental concepts like lambda calculus, denotational semantics thereby concentrating on the main points provided by these theories. Others topics in the book include concurrency, program components, object oriented programming and inter-language interoperability. The book also contains a special chapter on logic programming that demonstrates the importance of programming methods for different kinds of problems.');

-- --------------------------------------------------------

--
-- Table structure for table `ece`
--

CREATE TABLE `ece` (
  `Title` varchar(60) NOT NULL,
  `Author` varchar(60) NOT NULL,
  `Quantity` int(3) NOT NULL,
  `Img_Path` varchar(60) NOT NULL,
  `Description` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `ece`
--

INSERT INTO `ece` (`Title`, `Author`, `Quantity`, `Img_Path`, `Description`) VALUES
('Ad Hoc Network', 'B. S. Manoj', 70, 'Books frontpage/ECE/Ad.jpg', 'This book provides a comprehensive yet easy coverage of ad hoc and sensor networks and fills the gap of existing literature in this growing field. It emphasizes that there is a major interdependence among various layers of the network protocol stack. Contrary to wired or even one-hop cellular networks, the lack of a fixed infrastructure, the inherent mobility, the wireless channel, and the underlying routing mechanism by ad hoc and sensor networks introduce a number of technological challenges that are difficult to address within the boundaries of a single protocol layer.All existing textbooks on the subject often focus on a specific aspect of the technology, and fail to provide critical insights on cross-layer interdependencies. To fully understand these intriguing networks, one need to grasp specific solutions individually, and also the many interdependencies and cross-layer interactions.'),
('Analog Communication System', 'K C Raveendrana', 80, 'Books frontpage/ECE/ACS.jpg', 'Provides a detailed, unified treatment of theoretical and practical aspects of digital and analog communication systems, with emphasis on digital communication systems. Integrates theory—keeping theoretical details to a minimum—with over 60 practical, worked examples illustrating real-life methods. Emphasizes deriving design equations that relate performance of functional blocks to design parameters. Illustrates how to trade off between power, band-width and equipment complexity while maintaining an acceptable quality of performance. Material is modularized so that appropriate portions can be selected to teach several different courses. Includes over 300 problems and an annotated bibliography in each chapter.'),
('Analog Electronic Circuits', 'S N Ali', 60, 'Books frontpage/ECE/AEC.jpg', 'This book presents a collection of analog electronic circuits based on the op-amp, supported by a wealth of practical detail which will enable the reader to speedily select, build and test a desired circuit. The book is primarily intended to be a practical reference volume rather than a teaching text. Readers will discover an extensive and invaluable source of functional and established analog circuits, from integrators and differentiators to logarithmic amplifiers, from filters to instrumentation amplifiers. The circuits are grouped according to function, and the approach is to build up slowly from the basic textbook examples towards a series of practical, workable circuits. Students who need to build and test particular types of analog circuitry as part of an assignment or project based activities will find this book invaluable. Professional engineers will also find the book useful for design and development work. The coverage is extensive and up-to-date, and provides a wealth of technical advice.'),
('Avionics', 'Dale R Cundy', 70, 'Books frontpage/ECE/A.jpg', 'This unique book offers a non-technical, non-manual-style presentation of basic avionics. Focusing primarily on navigation, it provides a basic understanding of avionics designed to serve as both a textbook for students and a reference for practicing technicians.'),
('CAD for VLSI Design', 'N N Chiplunkar', 90, 'Books frontpage/ECE/CAD.jpg', 'This book leads students through the complete process of building a ready-to-fabricate CMOS integrated circuit using popular commercial design software. Detailed tutorials include step-by-step instructions and screen shots of tool windows and dialog boxes. This hands-on book is for use in conjunction with a primary textbook on digital VLSI.'),
('Congnitive Radio', 'Andrea J Goldsmith', 90, 'Books frontpage/ECE/CR.jpg', 'This book gives a comprehensive overview of the medium access control (MAC) principles in cognitive radio networks, with a specific focus on how such MAC principles enable different wireless systems to coexist in the same spectrum band and carry out spectrum sharing.  From algorithm design to the latest developments in the standards and spectrum policy, readers will benefit from leading-edge knowledge of how cognitive radio systems coexist and share spectrum resources.  Coverage includes cognitive radio rendezvous, spectrum sharing, channel allocation, coexistence in TV white space, and coexistence of heterogeneous wireless systems.'),
('Control Systems', 'Kumar A. Anand', 80, 'Books frontpage/ECE/CS.jpg', 'Control Systems: Theory and Applications is designed to meet the requirements of undergraduate programs in electrical, instrumentation, electronics and communication and other allied engineering disciplines. This book presents a comprehensive treatment of the fundamentals of control system theory with an emphasis on its practical applications. It covers a range of topics from the conventional to the modern and from the non-linear to the basic digital control systems, along with an introduction on the applications of fuzzy logic in control systems. It also provides an exhaustive coverage on continuous-time and discrete-time systems and the time-domain and frequency-domain analysis of control systems. The user-friendly approach and rich pedagogy will help students to enhance their problem-solving skills and enable them to apply the theories to the design and analysis of control systems.'),
('Digital Communication System', 'Simon Haykin', 70, 'Books frontpage/ECE/DCS.jpg', 'Offers the most complete, up-to-date coverage available on the principles of digital communications. Focuses on basic issues, relating theory to practice wherever possible. Numerous examples, worked out in detail, have been included to help the reader develop an intuitive grasp of the theory. Topics covered include the sampling process, digital modulation techniques, error-control coding, robust quantization for pulse-code modulation, coding speech at low bit radio, information theoretic concepts, coding and computer communication. Because the book covers a broad range of topics in digital communications, it should satisfy a variety of backgrounds and interests.'),
('Digital Electronics', 'Anil K. Maini', 70, 'Books frontpage/ECE/DE.jpg', 'Beginning with the fundamentals such as logic families, number systems, Boolean algebra and logic gates, and combinational circuits, Digital Electronics proceeds on to cover the applied aspects like sequential logic, ASM, programmable logic devices, converters and semiconductor memories. All the chapters in the book begin with outlining the contents of the chapters and include numerous solved examples and review questions to enhance the understanding of key concepts. \r\n\r\nOwing to its lucid style of presentation and a large number of numerical exercises and multiple choice questions at the end of the chapters, the book also serves as a self-preparatory material for students. '),
('Digital Logic System', 'D. Cilleti Micahel', 60, 'Books frontpage/ECE/DLS.jpg', 'For the latest digital principles, techniques, and hardware, look no further than this up-to-date edition! Practical, easy-to-understand coverage of the basics of digital design is provided, along with information on the necessary hardware to implement the design, and VHDL programming language for programming PLD devices. Everything from basic programming concepts to microprocessors and microcontrollers is featured, with updated coverage of CMOS sub-families and IC packages that reflect recent industry changes.'),
('Digital Signal Processing', 'Lizhe Tan', 70, 'Books frontpage/ECE/DSP.jpg', 'In the trademark style of the author, this book too presents the complicated world of digital signal processing to the students, in an exceedingly effortless manner. In this revision, the authors have taken care to update the text with the latest developments in the field and a new addition is the chapter on Discrete Time Random Signal Processing. Multiple references to applications make the subject come alive for the reader, as do the pedagogical features. In the use of MATLAB simulations and multiple illustrations, Digital Signal Processing, comes as a handy guide for all electronics, communication, computer science engineers for whom this is a core subject of study at the undergraduate level.'),
('Embedded Systems', 'I A Dhotre', 70, 'Books frontpage/ECE/ES.jpg', 'The book provides a comprehensive coverage on design and development of embedded hardware, firmware, their integration, and management of embedded system development process. This new edition has been thoroughly updated to cover all the latest developments in the fast changing fields. The book elucidates the concepts from elementary to advanced levels in simple language and supported with self-assessments questions and lab assignments.'),
('Multimedia Systems', 'Gibson', 80, 'Books frontpage/ECE/MS.jpg', 'This book describes the design of advanced multimedia systems in depth. It explores the characteristics of multimedia systems, identifies design challenges, examines the current and emerging technologies that support advanced multimedia systems, explains design methodologies and implementation techniques for convert-ing the design to produce efficient, flexible and reliable applications. Technologies discussed in this book include those required for distributed multi-media messaging. There is a growing need to manage widely distributed data in a timely and effective manner. The goal of the book is to help students of computer science to learn about the design compo-nents of a real-world multimedia solution for an enterprise. The book is divided into four major groupings of chapters that present relevant technologies-development methodologies, data modeling, and design-in a congruous manner. The end-of-chapter exercises encourage students to apply what they have learned through actual design and implementation. Professionals will enjoy exploring and building upon new concepts and methodologies presented in this book.'),
('Robotics Engineering', 'Rebecca Sjonger', 80, 'Books frontpage/ECE/RE.jpg', 'Robotics is an applied engineering science that has been referred to as a combination of machine tool technology and computer science. It includes diverse fields such as machine design, control theory, microelectronics, computer programming, artificial intelligence, human factors and production theory. The present book provides a comprehensive introduction to robotics. The book covers a fair amount of kinematics and dynamics of the robots. It also covers the sensors and actuators used in robotics system. This book will be useful for mechanical, electrical, electronics and computer engineering students. Key Features: Latest technological developments in robotics Robotic classifications, robot programming, robotic sensors and actuators. Kinematics and dynamic analysis of the Robot Modular systems in robotics Advances in Robotics systems Fuzzy logic control in Robotic systems Biped robot Bio-mimetic robot Robot safety and layout Robot calibration Numerical examples Relative merits and demerits of different robot systems'),
('Signals and System', 'S Poornachandra', 80, 'Books frontpage/ECE/SS.jpg', 'This comprehensive exploration of signals and systems develops continuous-time and discrete-time concepts/methods in parallel highlighting the similarities and differences and features introductory treatments of the applications of these basic methods in such areas as filtering, communication, sampling, discrete-time processing of continuous-time signals and feedback. Relatively self-contained, the text assumes no prior experience with system analysis, convolution, Fourier analysis or Laplace and z-transforms.');

-- --------------------------------------------------------

--
-- Table structure for table `llb`
--

CREATE TABLE `llb` (
  `Title` varchar(60) NOT NULL,
  `Author` varchar(60) NOT NULL,
  `Quantity` int(3) NOT NULL,
  `Img_Path` varchar(60) NOT NULL,
  `Description` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `llb`
--

INSERT INTO `llb` (`Title`, `Author`, `Quantity`, `Img_Path`, `Description`) VALUES
('Banking Law', 'Sukhvinder Mishra', 80, 'Books frontpage/LLB/BnL.jpg', 'This book is  published with the idea of presenting some of the key concepts of banking law for students pursuing law, both for undergraduate and post graduate courses and other professional courses as well. The framework of the book has been designed keeping in mind the requirements of course work. The present edition covers chapters on structure of banking in India, the role of the Reserve Bank of India, the relationship of bankers and customers, garnering of deposits and use of funds by banks. It also explains in detail the Banking Regulation Act, 1949, the Negotiable Instruments Act, 1881 and the Debt Recovery laws. The chapters contain extensive references of case laws, RBI circulars and reading material. The book covers the latest developments in the banking industry and policy. In view of the detailed coverage of all the topics, this book will be invaluable for students pursuing LL.B and LL.M and professional courses like Company Secretary and Chartered Accountancy and also for lawyers and bankers.'),
('Business Law', 'John A. Wiles', 80, 'Books frontpage/LLB/BL.jpg', 'Business law as a subject area deals with laws that dictate how to start, buy, manage and close or sell any type of business. Hence, knowledge of business laws assumes great importance for anyone who is starting a business or for any business manager or chartered accountant. \r\n\r\nThe content coverage of the book ensures that it caters to the needs of students pursuing B.Com, BBM and MBA courses taught in various Indian universities. The book is also relevant for students pursuing professional courses like ICWA intermediate course. The book is written in concise and lucid manner using several examples, case studies and exercises to make the content interesting and authentic. \r\nFeatures Includes more than 250 case studies'),
('Company Law', 'S S Gulshan', 80, 'Books frontpage/LLB/CL.jpg', 'The book presents a thorough study of all the new concepts and changes made in Company Law since 2013, including topics such as requirement of minimum share capital, related party transactions, Audit Committees, clause 49 of the Listing Agreement etc. This book has been updated with special resolutions, use of common seal, class action suits, shareholders rights, provisions for corporate social responsibility etc.'),
('Corporate Law', 'Anjali Arora', 80, 'Books frontpage/LLB/CrL.jpg', 'This book provides a thorough examination of the underlying principles of the law regulating companies in Australia. It facilitates a straightforward understanding of an area that is easily obscured by the complexity and detail of its rules. \r\nThis is an easy to understand text, written in a straightforward style. It imparts a solid understanding of the important topics of corporate law. \r\nCorporate Law is valuable for students approaching the subject for the first time, and for those seeking a deeper understanding of corporate law, as it presents a logical and thorough analysis of the necessary doctrine. It is an indispensable text that gives students a solid understanding of the important areas of corporate law. (less)'),
('Environment Law', 'Alok Pandey', 80, 'Books frontpage/LLB/EL.jpg', 'This book is not restricted to the regular collection of statutes found in most run-of-the-mill compilations, and is a first ever compilation of such a wide array of legislations concerning the environment and laws relating to it. Not only the Acts that directly address environmental issues, but also every aspect of the Central and State Acts, Rules, Policy Documents, International Treaties and Conventions that concern the environment has been looked into and relevant extracts given.'),
('International Law', 'Ian Brownlie', 80, 'Books frontpage/LLB/IL.jpg', 'This book explains the following topics: The sources of international law, The subjects of international law, International institutions, The prohibition against the use of force, Human Rights, International environmental law, The relationship between international and national law, State responsibility, Feminist perspectives on international law, Dispute settlement.'),
('Labour Law', 'S C Srivastava', 80, 'Books frontpage/LLB/LL.jpg', 'The primary aim of this book is to familiarise you with labour law which is dealt with herein and which you are expected to know much about at the end of your reading through. Topics covered includes: History and Sources of Nigerian Labour Law, The Contract of Employment, Employer and Employee - Duties and Obligations, Formations of Contract of Employment and its Effects, Freedom of Contract and Restrictions Thereon, Common Law Implied Terms, Employers Vicarious Liability, '),
('Law of Arbitration', 'Dr. P.C. Markanda', 70, 'Books frontpage/LLB/LA.jpg', 'This is the only book in the market which deals with the principles of Arbitration law in India rather than a section wise commentary of the provisions of the Indian Arbitration Act. Moreover the book deals with the principles of law based on the stages of the arbitration proceeding as a lawyer would experience whilst conducting an arbitration proceeding. Hence, the book is a practical guide to the conduct of arbitration proceeding which no other book currently in the market deals with. The chapters leads a reader through a step by step stage of the arbitration proceedings. In addition to the aforesaid, the book sets out the legal principles fully supported by case laws as laid down by different courts in the country. From practical usage point of view by practitioners and students, the book is being published in a single volume as all other books that have more than one volume which makes it cumbersome & less user friendly. Importantly, since the book deals with principles of law in arbitration it is more useful than section wise commentary as users need not read the whole case law to cull out the principles to put to practical use unlike a section wise commentary approach.'),
('Law of Contract', 'Dr. Avtar Singh', 80, 'Books frontpage/LLB/LOC.jpg', 'This book is an attempt to draw such an outline of the principles of the law of Contract as may be useful to students, and, perhaps, convenient to those who are engaged in the teaching of law. Author tried to show how a contract is made, what is needed to make it binding, what its effect is, how its terms are interpreted, and how it is discharged and comes to an end.'),
('Law of Torts & Consumer', 'Justice G P Singh', 70, 'Books frontpage/LLB/LT.jpg', 'This book covers the following topics: Overview Of Tort Law, Proximate cause, Defense to a personal injury case, Contributory fault, Modification of duty by status and relationships, Intentional Torts.'),
('Property Law', 'Sheldon F. Kurtz', 80, 'Books frontpage/LLB/PL.jpg', 'This book explains the following topics: Corporate Social Responsibility and Business Ethics, Courts and the Legal Process, Constitutional Law and US Commerce, Administrative Law, Criminal Law, Contracts, Introduction to Property: Personal Property and Fixtures, Intellectual Property, The Nature and Regulation of Real Estate and the Environment, The Transfer of Real Estate by Sale, Landlord and Tenant Law, Estate Planning: Wills, Estates, and Trusts, Bailments and the Storage, '),
('Tax Law', 'S R Myneni', 70, 'Books frontpage/LLB/TL.jpg', 'This easy-to-read book covers the entire gamut of direct and indirect taxes. The first eight chapters deal with direct taxes and generation of income from different sources. The last five chapters focus on different forms of indirect taxes. This text lucidly explains the acts, rules, sections, laws of direct and indirect taxes with a view to integrating the relevance of these laws with tax planning. The text fosters a clear understanding of the principles relating to computation of taxable income under each head of income. It covers different types of excise duties, methods of valuation for customs, types of transactions under the Central Sales Tax Act, variants of VAT and different methods of computation of VAT and service tax for management and professional services. A number of solved Illustrations at the end of each chapter are provided for easy comprehension of the subject. These along with chapter end questions consisting of short answer questions, long answer questions and exercises, enhance its value as a text. This text is intended for the undergraduate students of management, commerce and law (BBA, BCom and BL or LLB). Students pursuing professional courses such as CA, BCS (Bachelor of Corporate Secretaryship) and the aspirants of Civil Services Examinations will also find the text immensely useful.');

-- --------------------------------------------------------

--
-- Table structure for table `me`
--

CREATE TABLE `me` (
  `Title` varchar(60) NOT NULL,
  `Author` varchar(60) NOT NULL,
  `Quantity` int(3) NOT NULL,
  `Img_Path` varchar(60) NOT NULL,
  `Description` varchar(2000) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Indexes for dumped tables
--

--
-- Indexes for table `bme`
--
ALTER TABLE `bme`
  ADD PRIMARY KEY (`Title`);

--
-- Indexes for table `ce`
--
ALTER TABLE `ce`
  ADD PRIMARY KEY (`Title`);

--
-- Indexes for table `cse`
--
ALTER TABLE `cse`
  ADD PRIMARY KEY (`Title`);

--
-- Indexes for table `ece`
--
ALTER TABLE `ece`
  ADD PRIMARY KEY (`Title`);

--
-- Indexes for table `llb`
--
ALTER TABLE `llb`
  ADD PRIMARY KEY (`Title`);

--
-- Indexes for table `me`
--
ALTER TABLE `me`
  ADD PRIMARY KEY (`Title`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
